project:
    waves             : wave1
    machinecount      : 2
machine1:
    machineName       : TESTXXX01
    subnetIDs         : [subnet-XXXXX]
    securitygroupIDs  : [sg-XXXXX]
    instanceType      : t2.micro
    iamRole           : None
    tenancy           : SHARED
    tags              :
       count          : 3
       key1           : Name
       value1         : TESTXXX01
       key2           : migrated
       value2         : 'true'
       key3           : environment
       value3         : PROD
machine2:
    machineName       : TESTXXX02
    subnetIDs         : [subnet-XXXXX]
    securitygroupIDs  : [sg-XXXXX]
    instanceType      : t2.micro
    iamRole           : None
    tags              :
       count          : 3
       key1           : Name
       value1         : TESTXXX01
       key2           : migrated
       value2         : 'true'
       key3           : environment
       value3         : QA
       